### PR TITLE
implement `asyncJuxtCat` and `asyncMapCat`

### PR DESCRIPTION
**Pull request by nitzo**

### CODE REVIEW

**Comment by uriva** [comment]
do we really want to append async to all of the functions names? will we have a sync version as well?

**Comment by uriva** [comment]
LGTM

**Comment by nitzo** [comment]
I can start removing it and do what we did in gamla (in js it's even easier) to make all functions agnostic. 99% of the time the async version will work just fine for sync code. wdyt ?

**Comment by uriva** [comment]
sorry missed this

ideally we want generic versions which either return a value or a promise. not sure how easy this is.

if it is then for a function X i would have
X - generic
syncX - sync version
asyncX - async version

(i'm guessing the difference in runtime between the generic version and async/sync would be neglibible, but if i'm wrong then we would have the sync/async versions to optimize)

**Pull request merged**
